### ISSUE TITLE
Asset doesn't downloads from bonsai 

### ISSUE THREAD

**Issue by chukynax** [alerta/sensu-alerta-handler#13]
{"assets":null,"component":"pipelined","handler":"alerta","level":"info","msg":"event pipe handler executed","namespace":"default","output":"sh: 1: sensu-alerta-handler: not found\n","status":127,"time":"2019-09-19T12:50:33+03:00"}

**Comment by satterly** [comment]
This issue is blocked waiting on more information. The description or subsequent comments do not provide enough information to triage, investigate or resolve the issue. Please review the description against the [issue template](https://raw.githubusercontent.com/alerta/.github/master/.github/ISSUE_TEMPLATE/bug_report.md) and ensure all relevant information is included. If you do not know what is expected you can ask on [Gitter chat](https://gitter.im/alerta/chat).

**Comment by chukynax** [comment]
i took information from here https://bonsai.sensu.io/assets/alerta/sensu-alerta-handler

i filled up asset file like this: 
```
---
type: Asset
api_version: core/v2
metadata:
  name: sensu-alerta-handler_linux_amd64
  labels: 
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/alerta/sensu-alerta-handler
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/alerta/sensu-alerta-handler
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 1.0.4
    io.sensu.bonsai.namespace: alerta
    io.sensu.bonsai.name: sensu-alerta-handler
    io.sensu.bonsai.tags: alerta
spec:
  url: https://assets.bonsai.sensu.io/d42a4050b8ae95300057486be8daf6b749aa3414/sensu-alerta-handler_1.0.4_linux_amd64.tar.gz
  sha512: 50090697a8378d0c0a88c75fde0242866028b67f2bc8125dab88ff68cb5c3ed763c8f517dd3999f9a0457ab63ab1411a9941f6250ded9009c84c7cea2ba07c9c
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
```
And setup handler:
```
{
	"type": "Handler",
	"api_version": "core/v2",
	"metadata": {
		"namespace": "default",
		"name": "alerta"
	},
	"spec": {
		"type": "pipe",
		"command": "sensu-alerta-handler",
		"env_vars": [
			"ALERTA_ENDPOINT=http://172.17.0.1:8090/alert",
			"timeout=10"
		],
		"timeout": 30
	}
}
```

Afterwards i recieve log error decribed in topic
